### ISSUE TITLE
GLFW_CHECK and GL_CHECK macro usage

### ISSUE THREAD

**Issue by rolandha** [deltacasttv/video-viewer#15]
You can not use these macros in combination with a conditional statement because they do not return a value.

Line 174 in videoviewer_internal.cpp e.g. make no sense:

if (!GLFW_CHECK(glfwInit()))

as the macro is a while loop:

#define GLFW_CHECK(stmt) do {
stmt;
PrintGLFWError(#stmt, FILE, LINE);
} while (0)

**Comment by julienalofs** [comment]
Thank you for the report @rolandha. Indeed, you are right.
Do not hesitate to create pull request because I'm not sure to be available quickly to fix this.
