### ISSUE TITLE
Add support for MacOS

### ISSUE THREAD

**Issue by julienalofs** [deltacasttv/video-viewer#9]
Only Windows and Linux are supported for now. It would be great to support MacOS.

**Comment by julienalofs** [comment]
It seems the best way would be to integrate Metal for MacOS. See https://github.com/glfw/glfw/issues/1456

**Comment by julienalofs** [comment]
here is a link about programming Metal in C++: https://developer.apple.com/videos/play/wwdc2022/10160/

**Comment by julienalofs** [comment]
Another alternative would be to migrate to Vulkan because GLFW now supports Vulkan on macOS via MoltenVK (https://www.glfw.org/docs/3.3/news.html#moltenvk_33).

GLFW Vulkan guide: https://www.glfw.org/docs/3.3/vulkan_guide.html

**Comment by bedwardly-down** [comment]
I’m not sure how stable or usable this is, but has anyone fully explored it yet? https://github.com/openglonmetal/MGL

**Comment by julienalofs** [comment]
Here are some interesting information: https://stackoverflow.com/questions/65802625/develop-using-opengl-4-x-on-osx-big-sur/
